#!/usr/bin/env node
/**
 * Sync the README's live-deployment line from src/config/deployment.json so the
 * contract address is never hardcoded by hand. Rewrites the region between the
 * <!-- deployment:start --> / <!-- deployment:end --> markers in README.md.
 *
 * Run standalone (`node scripts/sync-readme.mjs`) or automatically at the end
 * of scripts/deploy.mjs. Idempotent; safe to run any number of times.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

// Explorer base for studionet — mirrors EXPLORER_URL in src/config/chain.ts.
const EXPLORER_URL = 'https://explorer-studio.genlayer.com'

const START = '<!-- deployment:start (generated by scripts/sync-readme.mjs from src/config/deployment.json; do not edit by hand) -->'
const END = '<!-- deployment:end -->'

export function syncReadme() {
  const deployPath = path.join(root, 'src', 'config', 'deployment.json')
  const readmePath = path.join(root, 'README.md')
  if (!fs.existsSync(deployPath)) {
    console.warn('sync-readme: no deployment.json; skipping')
    return false
  }

  const d = JSON.parse(fs.readFileSync(deployPath, 'utf8'))
  const explorer = `${EXPLORER_URL}/address/${d.address}`
  const block = [
    START,
    `**Live deployment.** Contract [\`${d.address}\`](${explorer}) on chain`,
    `${d.chainId} (${d.network}), recorded in`,
    '[`src/config/deployment.json`](src/config/deployment.json).',
    END,
  ].join('\n')

  const readme = fs.readFileSync(readmePath, 'utf8')
  const region = new RegExp(`${escapeRe(START)}[\\s\\S]*?${escapeRe(END)}`)
  if (!region.test(readme)) {
    console.warn('sync-readme: markers not found in README.md; skipping')
    return false
  }

  const next = readme.replace(region, block)
  if (next !== readme) {
    fs.writeFileSync(readmePath, next)
    console.log(`sync-readme: README.md ← ${d.address}`)
  } else {
    console.log('sync-readme: README.md already current')
  }
  return true
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

if (import.meta.url === `file://${process.argv[1]}`) syncReadme()
